import type { Metadata } from 'next'
import { Poppins} from 'next/font/google'
import localFont from 'next/font/local'

import './globals.css'

const poppins = Poppins({ subsets: ['latin'], weight: ["100", "200", "300", "400", "500", "600"] })

const helvetica = localFont({
  src: [
    {
      path: '../public/fonts/HelveticaNeueMedium.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/HelveticaNeueBold.otf',
      weight: '700',
      style: 'bold',
    },
  ],
})


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  )
}
